### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by grumps-kennel** [tercoide/GauchoCAD#55]
root@live:~/libredwg#     sh autogen.sh
+ rm -rf autom4te.cache config.status
+ test -d .git -a -f build-aux/git-version-gen
+ git fetch --tags
+ rm .tarball-version
rm: cannot remove '.tarball-version': No such file or directory
++ build-aux/git-version-gen .tarball-version
+ v=0.11.1.300_cc1a
+ echo 0.11.1.300_cc1a
+ echo 0.11.1.300_cc1a
+ set -e
+ autoreconf --install --symlink -I m4
autogen.sh: line 24: autoreconf: command not found
root@live:~/libredwg#     ./configure --enable-trace
bash: ./configure: No such file or directory
root@live:~/libredwg# 

Trying to create a live cd of debeian dog with no systemd or user account and need a cad software to create drawings for 3D printing.

**Comment by tercoide** [comment]
Hello there. This program has no releases yet.

**Comment by grumps-kennel** [comment]
I kinda guessed that, I persevered and got it to install via the given
instructions with a few edits and addons.
Only to discover there are only samples and tests within.
Do you have an envisaged release date?
